* Tutor Session Week 14

* Before we start

- Attendance Taking

* Exercise 1

"Unique paths"

#+BEGIN_QUOTE
Image you have a grid of r rows and c columns. You are standing at the
top left corner of a grid (s) and you want to move to a goal (g). You
can move through the grid only by moving right or down.  For any two
given integers (r,c), how many unique paths exist to get from s to g?

For a 2x2 grid the answer is 2. You can go down and right, or right
and down:

 s x
 x g

What for a grid r x c?
#+END_QUOTE

* Exercise 2

"Min-cost climbing stairs"

#+BEGIN_QUOTE
On a staircase, the i-th step has some non-negative cost cost[i]
assigned to it. The staircase starts at index i=0. Once you pay the
cost, you can either climb one or two steps. Design and implement an
algorithm to find the minimum cost to reach the top floor. You can
start your climb from either step index 0, or step index 1.

For example, given a staircase of 9 floors (from 0 to 8) and input
cost = [1, 100, 1, 1, 1, 100, 1, 1, 100, 1], the min-cost climb
starting from 0 is 6.
#+END_QUOTE

* Exercise 3

"Search in a bitonic array"

#+BEGIN_QUOTE
An array is bitonic if it is comprised of an increasing sequence of
integers followed immediately by a decreasing sequence of
integers. Write a program that, given a bitonic array of n distinct
integer values, determines whether a given integer is in the
array. Use O(lg n) compares in the worst case.

For example, the array [2,4,6,8,10,12,11,9,7,5,3] is bitonic, while
the following are not: [1,2,3], [1,2,3,2,3],[5].

Hint First, find the maximum integer using lg n compares—this divides
the array into the increasing and decreasing pieces.
#+END_QUOTE

* Exercise 4

Coin Change

Given an array of integer numbers that represent the values of each
coin, and given a target amount, determine the minimum number of coins
needed to create this amount. At first, try to solve this problem with
regular coins (i.e., 1,5,10,20,50), then try with different irregular
coin values (e.g., 1,7,12, 38).

Example 1 Given coin values (1, 2, 5,10,20,50), with Target amount =
7; solution = 2 coins (5,2) Target amount = 150; solution = 3 coins
(50,50,50) Target amount = 28; solution = 4 coins (20,5,2,1)

Example 2 Given coin values (1,4,6), with: Target amount = 7; solution
= 2 coins (6,1) Target amount = 9; solution = 3 coins (4,4,1)

Only the number of coins is required, the coins used are not important
for this exercise.
